proxies:
  - name: 1ï¸âƒ£ ğŸ® ç§»åŠ¨ğŸ”„ï¸è”é€š
    type: ss
    server: c57s1.jamjams3.net
    port: 30732
    password: avPyyJDsNBrhwTJA
    cipher: aes-256-gcm
    udp: true

  - name: 2ï¸âƒ£ ğŸ® è”é€šğŸ”„ï¸ç§»åŠ¨
    type: ss
    server: c57s2.jamjams3.net
    port: 30732
    password: avPyyJDsNBrhwTJA
    cipher: aes-256-gcm
    udp: true

  - name: 3ï¸âƒ£ ğŸ“¶ ç”µä¿¡
    type: vmess
    server: c57s3.jamjams3.net
    port: 30732
    uuid: ec0576a3-d218-44d3-8f81-25f827898e2b
    alterId: 0
    cipher: chacha20-poly1305

  - name: 4ï¸âƒ£ ğŸ—» æ—¥æœ¬å¤§é˜ªè½¯é“¶
    type: vmess
    server: c57s4.jamjams3.net
    port: 30732
    uuid: ec0576a3-d218-44d3-8f81-25f827898e2b
    alterId: 0
    cipher: chacha20-poly1305

  - name: 5ï¸âƒ£ ğŸ° è·å…°
    type: vmess
    server: c57s5.jamjams3.net
    port: 30732
    uuid: ec0576a3-d218-44d3-8f81-25f827898e2b
    alterId: 0
    cipher: chacha20-poly1305

proxy-groups:
  - name: ğŸš¥ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - 1ï¸âƒ£ ğŸ® ç§»åŠ¨ğŸ”„ï¸è”é€š
      - 2ï¸âƒ£ ğŸ® è”é€šğŸ”„ï¸ç§»åŠ¨
      - 3ï¸âƒ£ ğŸ“¶ ç”µä¿¡
      - 4ï¸âƒ£ ğŸ—» æ—¥æœ¬å¤§é˜ªè½¯é“¶
      - 5ï¸âƒ£ ğŸ° è·å…°

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 1ï¸âƒ£ ğŸ® ç§»åŠ¨ğŸ”„ï¸è”é€š
      - 2ï¸âƒ£ ğŸ® è”é€šğŸ”„ï¸ç§»åŠ¨
      - 3ï¸âƒ£ ğŸ“¶ ç”µä¿¡
      - 4ï¸âƒ£ ğŸ—» æ—¥æœ¬å¤§é˜ªè½¯é“¶
      - 5ï¸âƒ£ ğŸ° è·å…°

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš¥ èŠ‚ç‚¹é€‰æ‹©
      - DIRECT

  - name: ğŸ“ˆ ç½‘ç»œæµ‹é€Ÿ
    type: select
    proxies:
      - DIRECT
      - ğŸš¥ èŠ‚ç‚¹é€‰æ‹©

  - name: ğŸš€ ç›´è¿åŸŸå
    type: select
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©

  - name: ğŸªœ ä»£ç†åŸŸå
    type: select
    proxies:
      - ğŸš¥ èŠ‚ç‚¹é€‰æ‹©

  - name: ğŸ“± å¸¸è§è½¯ä»¶
    type: select
    proxies:
      - DIRECT

  - name: ğŸ—½ Google ä¸­å›½
    type: select
    proxies:
      - DIRECT

  - name: ğŸ Apple ä¸­å›½
    type: select
    proxies:
      - DIRECT

  - name: â˜ï¸ iCloud ä¸­å›½
    type: select
    proxies:
      - DIRECT

  - name: âœˆï¸ Telegram ä¸­å›½
    type: select
    proxies:
      - DIRECT

  - name: ğŸ  ç§æœ‰ç½‘ç»œ
    type: select
    proxies:
      - DIRECT

  - name: ğŸ’» å±€åŸŸç½‘å’Œä¿ç•™ IP åœ°å€
    type: select
    proxies:
      - DIRECT

  - name: ğŸš„ å›½å†… IP åœ°å€
    type: select
    proxies:
      - DIRECT

  - name: ğŸš« å¹¿å‘ŠåŸŸå
    type: select
    proxies:
      - REJECT

rule-providers:
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

rules:
  - RULE-SET,applications,ğŸ“± å¸¸è§è½¯ä»¶
  - DOMAIN-KEYWORD,ipv6,DIRECT
  - DOMAIN-KEYWORD,test,ğŸ“ˆ ç½‘ç»œæµ‹é€Ÿ
  - DOMAIN-SUFFIX,googleapis.cn,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,private,ğŸ  ç§æœ‰ç½‘ç»œ
  - RULE-SET,reject,ğŸš« å¹¿å‘ŠåŸŸå
  - RULE-SET,icloud,â˜ï¸ iCloud ä¸­å›½
  - RULE-SET,apple,ğŸ Apple ä¸­å›½
  - RULE-SET,google,ğŸ—½ Google ä¸­å›½
  - RULE-SET,proxy,ğŸªœ ä»£ç†åŸŸå
  - RULE-SET,direct,ğŸš€ ç›´è¿åŸŸå
  - RULE-SET,lancidr,ğŸ’» å±€åŸŸç½‘å’Œä¿ç•™ IP åœ°å€
  - RULE-SET,cncidr,ğŸš„ å›½å†… IP åœ°å€
  - RULE-SET,telegramcidr,âœˆï¸ Telegram ä¸­å›½
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼