name: Update fake-ip-user.yaml
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/workflows/delete-old-workflows.yml"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Generate geodata-fakeip-user.yaml
      run: |
        echo "update_version=$(date -d '+8 hours' +'%Y-%m-%d')" >> ${GITHUB_ENV}
        mkdir -p ./Clash/fake-ip-config/
        cat <<EOF > ./Clash/geodata-fakeip-user.yaml
        sniffer:
          enable: true
          parse-pure-ip: true
          sniff: {HTTP: {ports: [80, 8080-8880], override-destination: true}, TLS: {ports: [443, 8443]}, QUIC: {ports: [443, 8443]}}
          skip-domain: ['Mijia Cloud']

        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellCrash/master/public/fake_ip_filter.list | grep -v "#" | sed '/^\s*$/d' | sed "s/.*/'&'/g" | sed 's/^/    - /g' >> ./Clash/geodata-fakeip-user.yaml
        cat <<EOF >> ./Clash/geodata-fakeip-user.yaml
          default-nameserver:
            - https://223.5.5.5/dns-query
            - https://1.12.12.12/dns-query
          nameserver:
            - https://dns.alidns.com/dns-query#h3=true
            - https://doh.pub/dns-query
          nameserver-policy:
            'geosite:category-ads-all': rcode://success
            'geosite:microsoft@cn,apple-cn,google-cn,category-games@cn': [https://dns.alidns.com/dns-query#h3=true, https://doh.pub/dns-query,]
            'geosite:cn,private': [https://dns.alidns.com/dns-query#h3=true, https://doh.pub/dns-query]
            'geosite:geolocation-!cn': ['https://cloudflare-dns.com/dns-query#ðŸªœ ä»£ç†åŸŸå&h3=true', 'https://dns.google/dns-query#ðŸªœ ä»£ç†åŸŸå']
        EOF

    - name: Generate ruleset-fakeip-user.yaml
      run: |
        sed -e 's/geosite:category-ads-all/rule-set:ads/' \
        -e 's/geosite:microsoft@cn,apple-cn,google-cn,category-games@cn/rule-set:microsoft-cn,apple-cn,google-cn,games-cn/' \
        -e 's/geosite:cn,private/rule-set:cn,private/' \
        -e 's/geosite:geolocation-\!cn/rule-set:proxy/' ./Clash/geodata-fakeip-user.yaml > ./Clash/ruleset-fakeip-user.yaml

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "æ›´æ–°äºŽ ${update_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN
      run: |
        cd ./Clash/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/Clash/${file}"
        done
